### ISSUE TITLE
[BUG] Send to Tensorboard button not working

### ISSUE THREAD

**Issue by AmirKhooj** [dessa-oss/atlas#118]
**Platform & setup**
Ubuntu 18.04
Python 3.6

**Describe the bug**
There are two problems actually: 
1) to enable tensorboard as per documents, I do:
```
import foundations
foundations.set_tensorboard_logdir("/the/shared/dir/in/host/with/docker")
```
This fails with below error:
`TypeError: 'module' object is not callable`

If you look into the `foundations.__file__` directory you would see that the set_tensorboard_logdir is a python module there which has a set_tensorboard_logdir function inside. So, it means to call that set_tensorboard_logdir function we can do as below:

```
import foundations
import foundations.set_tensorboard_logdir as tb
tb.set_tensorboard_logdir("/the/shared/dir/in/host/with/docker")
```

is this correct??

2) My second question depends on the answer to the first question, with the workaround above, when I launch a project and click the "Send to Tensorboard" button, a new tab opens up and there is nothing in it. It will not load the "localhost:5959" address. If I manually enter that address it loads a tensorboard session but it is empty, seems that it cannot find the logdir for tensorboard. It is worthy to note that the below directory is empty: 
**~/.foundations/tensorboard/work_dir/**
however the below dir has the tensorboard event files:
 **~/.foundations/job_data/archive/JOBID/synced_directories/__tensorboard__/**

**To Reproduce**
Mentioned above
**Expected behavior**
Send to Tensorboard should launch the tensorboard tab.

**Screenshots**

**Additional context / Stacktrace**
Add any other context about the problem here e.g. what system were you on? F9s trial environment? GCP? DGX?

**Comment by mohammedri** [comment]
Hey @AmirKhooj thanks for filing this issue - that's a great catch! We know what the problem is and will be releasing a PR soon. 

But in the meanwhile, I have a workaround for you:
1. In your Atlas environment, run `python -m site`
2. This should give you a bunch of paths, look for the one that ends with `/site-packages` and copy that entire path.
3. `cd <path_copied_above`
4. `cd atlas-server`
5. Open the `__main.py__` file there 
6. In lines 374 and 375, change `FOUNDATIONS_TENSORBOARD_HOST` --> `TENSORBOARD_HOST` and `FOUNDATIONS_TENSORBOARD_API` to `TENSORBOARD_API`.

We will have the fix out soon, thanks

**Comment by AmirKhooj** [comment]
thanks, will the steps mentioned above I can see Tensorboard tab now. 

I noticed that the "Send to Tensorboard" button is disabled till the job ends, is there any way I can see the Tensorboard graph while the job is running?

**Comment by mohammedri** [comment]
@AmirKhooj  unfortunately this feature is not supported yet, because we read the Tensorboard file from the artifact storage server, the artifacts are only packaged and available after the job finishes running. Essentially we wait until the end to upload everything to the artifact server and then create the symlinks when that button is pushed so that things appear where tensorboard is looking. 

Open to further discussion if you would like to ship a fix!
