### ISSUE TITLE
can't see tensorboard

### ISSUE THREAD

**Issue by foowaa** [dessa-oss/atlas#179]
**Platform & setup**
Ubuntu 16.04

**Describe the bug**
tensorboard cannot be loaded when I click **send to tensorboad**.
I use the cifar-tutorial and follow the readme, and I add `foundations.set_tensorboard_logdir('train_logs')` in the `driver.py`.
Then `foundations submit scheduler . driver.py`, I can see the job starts in GUI, but **send to tensorboad** button is useless.

**To Reproduce**
I describe the details above.

**Expected behavior**
**send to tensorboad** button is useless

**Screenshots**

**Additional context / Stacktrace**
Add any other context about the problem here e.g. what system were you on? F9s trial environment? GCP? DGX?

**Comment by phalix** [comment]
I have the same issue. Although the tensorboard container is running. I run on windows 10 with docker desktop.

**Comment by stingshen** [comment]
The two env names set in atlas-server are wrong:

https://github.com/dessa-oss/atlas/blob/master/atlas_server/src/atlas-server/__main__.py#L363

The env should be `TENSORBOARD_API_HOST` and `TENSORBOARD_API_HOST` instead of `FOUNDATIONS_TENSORBOARD_API_HOST` and `FOUNDATIONS_TENSORBOARD_API_HOST`.

After fixing the env names, the tensorboard launches successfully.

**Comment by foowaa** [comment]
> The two env names set in atlas-server are wrong:
> 
> https://github.com/dessa-oss/atlas/blob/master/atlas_server/src/atlas-server/__main__.py#L363
> 
> The env should be `TENSORBOARD_API_HOST` and `TENSORBOARD_API_HOST` instead of `FOUNDATIONS_TENSORBOARD_API_HOST` and `FOUNDATIONS_TENSORBOARD_API_HOST`.
> 
> After fixing the env names, the tensorboard launches successfully.

Thank U.
